// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.vo;

import java.util.List;

public class DashboardVO {
    private Long resourceTotal;
    private Long categoryTotal;
    private Long tagTotal;
    private Long leadTotal;
    private List<DashboardRecentResourceVO> recentResources;
    private List<DashboardRecentLeadVO> recentLeads;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DashboardVO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getResourceTotal() {
        return this.resourceTotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCategoryTotal() {
        return this.categoryTotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getTagTotal() {
        return this.tagTotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getLeadTotal() {
        return this.leadTotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<DashboardRecentResourceVO> getRecentResources() {
        return this.recentResources;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<DashboardRecentLeadVO> getRecentLeads() {
        return this.recentLeads;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResourceTotal(final Long resourceTotal) {
        this.resourceTotal = resourceTotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategoryTotal(final Long categoryTotal) {
        this.categoryTotal = categoryTotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTagTotal(final Long tagTotal) {
        this.tagTotal = tagTotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLeadTotal(final Long leadTotal) {
        this.leadTotal = leadTotal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRecentResources(final List<DashboardRecentResourceVO> recentResources) {
        this.recentResources = recentResources;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRecentLeads(final List<DashboardRecentLeadVO> recentLeads) {
        this.recentLeads = recentLeads;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DashboardVO)) return false;
        final DashboardVO other = (DashboardVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$resourceTotal = this.getResourceTotal();
        final java.lang.Object other$resourceTotal = other.getResourceTotal();
        if (this$resourceTotal == null ? other$resourceTotal != null : !this$resourceTotal.equals(other$resourceTotal)) return false;
        final java.lang.Object this$categoryTotal = this.getCategoryTotal();
        final java.lang.Object other$categoryTotal = other.getCategoryTotal();
        if (this$categoryTotal == null ? other$categoryTotal != null : !this$categoryTotal.equals(other$categoryTotal)) return false;
        final java.lang.Object this$tagTotal = this.getTagTotal();
        final java.lang.Object other$tagTotal = other.getTagTotal();
        if (this$tagTotal == null ? other$tagTotal != null : !this$tagTotal.equals(other$tagTotal)) return false;
        final java.lang.Object this$leadTotal = this.getLeadTotal();
        final java.lang.Object other$leadTotal = other.getLeadTotal();
        if (this$leadTotal == null ? other$leadTotal != null : !this$leadTotal.equals(other$leadTotal)) return false;
        final java.lang.Object this$recentResources = this.getRecentResources();
        final java.lang.Object other$recentResources = other.getRecentResources();
        if (this$recentResources == null ? other$recentResources != null : !this$recentResources.equals(other$recentResources)) return false;
        final java.lang.Object this$recentLeads = this.getRecentLeads();
        final java.lang.Object other$recentLeads = other.getRecentLeads();
        if (this$recentLeads == null ? other$recentLeads != null : !this$recentLeads.equals(other$recentLeads)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DashboardVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $resourceTotal = this.getResourceTotal();
        result = result * PRIME + ($resourceTotal == null ? 43 : $resourceTotal.hashCode());
        final java.lang.Object $categoryTotal = this.getCategoryTotal();
        result = result * PRIME + ($categoryTotal == null ? 43 : $categoryTotal.hashCode());
        final java.lang.Object $tagTotal = this.getTagTotal();
        result = result * PRIME + ($tagTotal == null ? 43 : $tagTotal.hashCode());
        final java.lang.Object $leadTotal = this.getLeadTotal();
        result = result * PRIME + ($leadTotal == null ? 43 : $leadTotal.hashCode());
        final java.lang.Object $recentResources = this.getRecentResources();
        result = result * PRIME + ($recentResources == null ? 43 : $recentResources.hashCode());
        final java.lang.Object $recentLeads = this.getRecentLeads();
        result = result * PRIME + ($recentLeads == null ? 43 : $recentLeads.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DashboardVO(resourceTotal=" + this.getResourceTotal() + ", categoryTotal=" + this.getCategoryTotal() + ", tagTotal=" + this.getTagTotal() + ", leadTotal=" + this.getLeadTotal() + ", recentResources=" + this.getRecentResources() + ", recentLeads=" + this.getRecentLeads() + ")";
    }
}
