// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.vo;

import java.util.List;

public class HomePageVO {
    private String siteName;
    private String seoTitle;
    private String seoKeywords;
    private String seoDescription;
    private String homeMainTitle;
    private String homeSubTitle;
    private String footerText;
    private List<CategoryVO> hotCategories;
    private List<ResourceListItemVO> recommendedResources;
    private List<FaqVO> faqList;
    private WechatConsultVO wechatConsult;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public HomePageVO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSiteName() {
        return this.siteName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSeoTitle() {
        return this.seoTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSeoKeywords() {
        return this.seoKeywords;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSeoDescription() {
        return this.seoDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getHomeMainTitle() {
        return this.homeMainTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getHomeSubTitle() {
        return this.homeSubTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFooterText() {
        return this.footerText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<CategoryVO> getHotCategories() {
        return this.hotCategories;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<ResourceListItemVO> getRecommendedResources() {
        return this.recommendedResources;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<FaqVO> getFaqList() {
        return this.faqList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WechatConsultVO getWechatConsult() {
        return this.wechatConsult;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSiteName(final String siteName) {
        this.siteName = siteName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSeoTitle(final String seoTitle) {
        this.seoTitle = seoTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSeoKeywords(final String seoKeywords) {
        this.seoKeywords = seoKeywords;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSeoDescription(final String seoDescription) {
        this.seoDescription = seoDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHomeMainTitle(final String homeMainTitle) {
        this.homeMainTitle = homeMainTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHomeSubTitle(final String homeSubTitle) {
        this.homeSubTitle = homeSubTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFooterText(final String footerText) {
        this.footerText = footerText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHotCategories(final List<CategoryVO> hotCategories) {
        this.hotCategories = hotCategories;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRecommendedResources(final List<ResourceListItemVO> recommendedResources) {
        this.recommendedResources = recommendedResources;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFaqList(final List<FaqVO> faqList) {
        this.faqList = faqList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWechatConsult(final WechatConsultVO wechatConsult) {
        this.wechatConsult = wechatConsult;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof HomePageVO)) return false;
        final HomePageVO other = (HomePageVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$siteName = this.getSiteName();
        final java.lang.Object other$siteName = other.getSiteName();
        if (this$siteName == null ? other$siteName != null : !this$siteName.equals(other$siteName)) return false;
        final java.lang.Object this$seoTitle = this.getSeoTitle();
        final java.lang.Object other$seoTitle = other.getSeoTitle();
        if (this$seoTitle == null ? other$seoTitle != null : !this$seoTitle.equals(other$seoTitle)) return false;
        final java.lang.Object this$seoKeywords = this.getSeoKeywords();
        final java.lang.Object other$seoKeywords = other.getSeoKeywords();
        if (this$seoKeywords == null ? other$seoKeywords != null : !this$seoKeywords.equals(other$seoKeywords)) return false;
        final java.lang.Object this$seoDescription = this.getSeoDescription();
        final java.lang.Object other$seoDescription = other.getSeoDescription();
        if (this$seoDescription == null ? other$seoDescription != null : !this$seoDescription.equals(other$seoDescription)) return false;
        final java.lang.Object this$homeMainTitle = this.getHomeMainTitle();
        final java.lang.Object other$homeMainTitle = other.getHomeMainTitle();
        if (this$homeMainTitle == null ? other$homeMainTitle != null : !this$homeMainTitle.equals(other$homeMainTitle)) return false;
        final java.lang.Object this$homeSubTitle = this.getHomeSubTitle();
        final java.lang.Object other$homeSubTitle = other.getHomeSubTitle();
        if (this$homeSubTitle == null ? other$homeSubTitle != null : !this$homeSubTitle.equals(other$homeSubTitle)) return false;
        final java.lang.Object this$footerText = this.getFooterText();
        final java.lang.Object other$footerText = other.getFooterText();
        if (this$footerText == null ? other$footerText != null : !this$footerText.equals(other$footerText)) return false;
        final java.lang.Object this$hotCategories = this.getHotCategories();
        final java.lang.Object other$hotCategories = other.getHotCategories();
        if (this$hotCategories == null ? other$hotCategories != null : !this$hotCategories.equals(other$hotCategories)) return false;
        final java.lang.Object this$recommendedResources = this.getRecommendedResources();
        final java.lang.Object other$recommendedResources = other.getRecommendedResources();
        if (this$recommendedResources == null ? other$recommendedResources != null : !this$recommendedResources.equals(other$recommendedResources)) return false;
        final java.lang.Object this$faqList = this.getFaqList();
        final java.lang.Object other$faqList = other.getFaqList();
        if (this$faqList == null ? other$faqList != null : !this$faqList.equals(other$faqList)) return false;
        final java.lang.Object this$wechatConsult = this.getWechatConsult();
        final java.lang.Object other$wechatConsult = other.getWechatConsult();
        if (this$wechatConsult == null ? other$wechatConsult != null : !this$wechatConsult.equals(other$wechatConsult)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof HomePageVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $siteName = this.getSiteName();
        result = result * PRIME + ($siteName == null ? 43 : $siteName.hashCode());
        final java.lang.Object $seoTitle = this.getSeoTitle();
        result = result * PRIME + ($seoTitle == null ? 43 : $seoTitle.hashCode());
        final java.lang.Object $seoKeywords = this.getSeoKeywords();
        result = result * PRIME + ($seoKeywords == null ? 43 : $seoKeywords.hashCode());
        final java.lang.Object $seoDescription = this.getSeoDescription();
        result = result * PRIME + ($seoDescription == null ? 43 : $seoDescription.hashCode());
        final java.lang.Object $homeMainTitle = this.getHomeMainTitle();
        result = result * PRIME + ($homeMainTitle == null ? 43 : $homeMainTitle.hashCode());
        final java.lang.Object $homeSubTitle = this.getHomeSubTitle();
        result = result * PRIME + ($homeSubTitle == null ? 43 : $homeSubTitle.hashCode());
        final java.lang.Object $footerText = this.getFooterText();
        result = result * PRIME + ($footerText == null ? 43 : $footerText.hashCode());
        final java.lang.Object $hotCategories = this.getHotCategories();
        result = result * PRIME + ($hotCategories == null ? 43 : $hotCategories.hashCode());
        final java.lang.Object $recommendedResources = this.getRecommendedResources();
        result = result * PRIME + ($recommendedResources == null ? 43 : $recommendedResources.hashCode());
        final java.lang.Object $faqList = this.getFaqList();
        result = result * PRIME + ($faqList == null ? 43 : $faqList.hashCode());
        final java.lang.Object $wechatConsult = this.getWechatConsult();
        result = result * PRIME + ($wechatConsult == null ? 43 : $wechatConsult.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "HomePageVO(siteName=" + this.getSiteName() + ", seoTitle=" + this.getSeoTitle() + ", seoKeywords=" + this.getSeoKeywords() + ", seoDescription=" + this.getSeoDescription() + ", homeMainTitle=" + this.getHomeMainTitle() + ", homeSubTitle=" + this.getHomeSubTitle() + ", footerText=" + this.getFooterText() + ", hotCategories=" + this.getHotCategories() + ", recommendedResources=" + this.getRecommendedResources() + ", faqList=" + this.getFaqList() + ", wechatConsult=" + this.getWechatConsult() + ")";
    }
}
