// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.vo;

import java.util.List;

public class HomeConfigVO {
    private String homeMainTitle;
    private String homeSubTitle;
    private String wechatId;
    private String wechatQrUrl;
    private String wechatTip;
    private List<Long> homeHotCategoryIds;
    private List<Long> homeRecommendedResourceIds;
    private List<Long> homeFaqIds;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public HomeConfigVO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getHomeMainTitle() {
        return this.homeMainTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getHomeSubTitle() {
        return this.homeSubTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWechatId() {
        return this.wechatId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWechatQrUrl() {
        return this.wechatQrUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWechatTip() {
        return this.wechatTip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<Long> getHomeHotCategoryIds() {
        return this.homeHotCategoryIds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<Long> getHomeRecommendedResourceIds() {
        return this.homeRecommendedResourceIds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<Long> getHomeFaqIds() {
        return this.homeFaqIds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHomeMainTitle(final String homeMainTitle) {
        this.homeMainTitle = homeMainTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHomeSubTitle(final String homeSubTitle) {
        this.homeSubTitle = homeSubTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWechatId(final String wechatId) {
        this.wechatId = wechatId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWechatQrUrl(final String wechatQrUrl) {
        this.wechatQrUrl = wechatQrUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWechatTip(final String wechatTip) {
        this.wechatTip = wechatTip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHomeHotCategoryIds(final List<Long> homeHotCategoryIds) {
        this.homeHotCategoryIds = homeHotCategoryIds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHomeRecommendedResourceIds(final List<Long> homeRecommendedResourceIds) {
        this.homeRecommendedResourceIds = homeRecommendedResourceIds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHomeFaqIds(final List<Long> homeFaqIds) {
        this.homeFaqIds = homeFaqIds;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof HomeConfigVO)) return false;
        final HomeConfigVO other = (HomeConfigVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$homeMainTitle = this.getHomeMainTitle();
        final java.lang.Object other$homeMainTitle = other.getHomeMainTitle();
        if (this$homeMainTitle == null ? other$homeMainTitle != null : !this$homeMainTitle.equals(other$homeMainTitle)) return false;
        final java.lang.Object this$homeSubTitle = this.getHomeSubTitle();
        final java.lang.Object other$homeSubTitle = other.getHomeSubTitle();
        if (this$homeSubTitle == null ? other$homeSubTitle != null : !this$homeSubTitle.equals(other$homeSubTitle)) return false;
        final java.lang.Object this$wechatId = this.getWechatId();
        final java.lang.Object other$wechatId = other.getWechatId();
        if (this$wechatId == null ? other$wechatId != null : !this$wechatId.equals(other$wechatId)) return false;
        final java.lang.Object this$wechatQrUrl = this.getWechatQrUrl();
        final java.lang.Object other$wechatQrUrl = other.getWechatQrUrl();
        if (this$wechatQrUrl == null ? other$wechatQrUrl != null : !this$wechatQrUrl.equals(other$wechatQrUrl)) return false;
        final java.lang.Object this$wechatTip = this.getWechatTip();
        final java.lang.Object other$wechatTip = other.getWechatTip();
        if (this$wechatTip == null ? other$wechatTip != null : !this$wechatTip.equals(other$wechatTip)) return false;
        final java.lang.Object this$homeHotCategoryIds = this.getHomeHotCategoryIds();
        final java.lang.Object other$homeHotCategoryIds = other.getHomeHotCategoryIds();
        if (this$homeHotCategoryIds == null ? other$homeHotCategoryIds != null : !this$homeHotCategoryIds.equals(other$homeHotCategoryIds)) return false;
        final java.lang.Object this$homeRecommendedResourceIds = this.getHomeRecommendedResourceIds();
        final java.lang.Object other$homeRecommendedResourceIds = other.getHomeRecommendedResourceIds();
        if (this$homeRecommendedResourceIds == null ? other$homeRecommendedResourceIds != null : !this$homeRecommendedResourceIds.equals(other$homeRecommendedResourceIds)) return false;
        final java.lang.Object this$homeFaqIds = this.getHomeFaqIds();
        final java.lang.Object other$homeFaqIds = other.getHomeFaqIds();
        if (this$homeFaqIds == null ? other$homeFaqIds != null : !this$homeFaqIds.equals(other$homeFaqIds)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof HomeConfigVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $homeMainTitle = this.getHomeMainTitle();
        result = result * PRIME + ($homeMainTitle == null ? 43 : $homeMainTitle.hashCode());
        final java.lang.Object $homeSubTitle = this.getHomeSubTitle();
        result = result * PRIME + ($homeSubTitle == null ? 43 : $homeSubTitle.hashCode());
        final java.lang.Object $wechatId = this.getWechatId();
        result = result * PRIME + ($wechatId == null ? 43 : $wechatId.hashCode());
        final java.lang.Object $wechatQrUrl = this.getWechatQrUrl();
        result = result * PRIME + ($wechatQrUrl == null ? 43 : $wechatQrUrl.hashCode());
        final java.lang.Object $wechatTip = this.getWechatTip();
        result = result * PRIME + ($wechatTip == null ? 43 : $wechatTip.hashCode());
        final java.lang.Object $homeHotCategoryIds = this.getHomeHotCategoryIds();
        result = result * PRIME + ($homeHotCategoryIds == null ? 43 : $homeHotCategoryIds.hashCode());
        final java.lang.Object $homeRecommendedResourceIds = this.getHomeRecommendedResourceIds();
        result = result * PRIME + ($homeRecommendedResourceIds == null ? 43 : $homeRecommendedResourceIds.hashCode());
        final java.lang.Object $homeFaqIds = this.getHomeFaqIds();
        result = result * PRIME + ($homeFaqIds == null ? 43 : $homeFaqIds.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "HomeConfigVO(homeMainTitle=" + this.getHomeMainTitle() + ", homeSubTitle=" + this.getHomeSubTitle() + ", wechatId=" + this.getWechatId() + ", wechatQrUrl=" + this.getWechatQrUrl() + ", wechatTip=" + this.getWechatTip() + ", homeHotCategoryIds=" + this.getHomeHotCategoryIds() + ", homeRecommendedResourceIds=" + this.getHomeRecommendedResourceIds() + ", homeFaqIds=" + this.getHomeFaqIds() + ")";
    }
}
