// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.vo;

import java.math.BigDecimal;

public class ResourceRelationVO {
    private Long id;
    private String title;
    private String coverImage;
    private BigDecimal displayPrice;
    private String grade;
    private String scene;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ResourceRelationVO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCoverImage() {
        return this.coverImage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDisplayPrice() {
        return this.displayPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGrade() {
        return this.grade;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getScene() {
        return this.scene;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCoverImage(final String coverImage) {
        this.coverImage = coverImage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayPrice(final BigDecimal displayPrice) {
        this.displayPrice = displayPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGrade(final String grade) {
        this.grade = grade;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setScene(final String scene) {
        this.scene = scene;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ResourceRelationVO)) return false;
        final ResourceRelationVO other = (ResourceRelationVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$coverImage = this.getCoverImage();
        final java.lang.Object other$coverImage = other.getCoverImage();
        if (this$coverImage == null ? other$coverImage != null : !this$coverImage.equals(other$coverImage)) return false;
        final java.lang.Object this$displayPrice = this.getDisplayPrice();
        final java.lang.Object other$displayPrice = other.getDisplayPrice();
        if (this$displayPrice == null ? other$displayPrice != null : !this$displayPrice.equals(other$displayPrice)) return false;
        final java.lang.Object this$grade = this.getGrade();
        final java.lang.Object other$grade = other.getGrade();
        if (this$grade == null ? other$grade != null : !this$grade.equals(other$grade)) return false;
        final java.lang.Object this$scene = this.getScene();
        final java.lang.Object other$scene = other.getScene();
        if (this$scene == null ? other$scene != null : !this$scene.equals(other$scene)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ResourceRelationVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $coverImage = this.getCoverImage();
        result = result * PRIME + ($coverImage == null ? 43 : $coverImage.hashCode());
        final java.lang.Object $displayPrice = this.getDisplayPrice();
        result = result * PRIME + ($displayPrice == null ? 43 : $displayPrice.hashCode());
        final java.lang.Object $grade = this.getGrade();
        result = result * PRIME + ($grade == null ? 43 : $grade.hashCode());
        final java.lang.Object $scene = this.getScene();
        result = result * PRIME + ($scene == null ? 43 : $scene.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ResourceRelationVO(id=" + this.getId() + ", title=" + this.getTitle() + ", coverImage=" + this.getCoverImage() + ", displayPrice=" + this.getDisplayPrice() + ", grade=" + this.getGrade() + ", scene=" + this.getScene() + ")";
    }
}
