// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.vo;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

public class ResourceDetailVO {
    private Long id;
    private String title;
    private String slug;
    private Long categoryId;
    private String categoryName;
    private String summary;
    private String coverImage;
    private BigDecimal displayPrice;
    private String grade;
    private String scene;
    private List<String> previewImages;
    private List<TagVO> tags;
    private LocalDateTime publishTime;
    private LocalDateTime updatedAt;
    private List<String> contentItems;
    private String descriptionHtml;
    private String usageNotice;
    private List<FaqVO> faqList;
    private WechatConsultVO wechatConsult;
    private List<ResourceRelationVO> relatedResources;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ResourceDetailVO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSlug() {
        return this.slug;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCategoryId() {
        return this.categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCategoryName() {
        return this.categoryName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSummary() {
        return this.summary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCoverImage() {
        return this.coverImage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDisplayPrice() {
        return this.displayPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGrade() {
        return this.grade;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getScene() {
        return this.scene;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getPreviewImages() {
        return this.previewImages;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<TagVO> getTags() {
        return this.tags;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getPublishTime() {
        return this.publishTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getContentItems() {
        return this.contentItems;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescriptionHtml() {
        return this.descriptionHtml;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUsageNotice() {
        return this.usageNotice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<FaqVO> getFaqList() {
        return this.faqList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WechatConsultVO getWechatConsult() {
        return this.wechatConsult;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<ResourceRelationVO> getRelatedResources() {
        return this.relatedResources;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSlug(final String slug) {
        this.slug = slug;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategoryId(final Long categoryId) {
        this.categoryId = categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategoryName(final String categoryName) {
        this.categoryName = categoryName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSummary(final String summary) {
        this.summary = summary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCoverImage(final String coverImage) {
        this.coverImage = coverImage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayPrice(final BigDecimal displayPrice) {
        this.displayPrice = displayPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGrade(final String grade) {
        this.grade = grade;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setScene(final String scene) {
        this.scene = scene;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPreviewImages(final List<String> previewImages) {
        this.previewImages = previewImages;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTags(final List<TagVO> tags) {
        this.tags = tags;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPublishTime(final LocalDateTime publishTime) {
        this.publishTime = publishTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContentItems(final List<String> contentItems) {
        this.contentItems = contentItems;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescriptionHtml(final String descriptionHtml) {
        this.descriptionHtml = descriptionHtml;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUsageNotice(final String usageNotice) {
        this.usageNotice = usageNotice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFaqList(final List<FaqVO> faqList) {
        this.faqList = faqList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWechatConsult(final WechatConsultVO wechatConsult) {
        this.wechatConsult = wechatConsult;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRelatedResources(final List<ResourceRelationVO> relatedResources) {
        this.relatedResources = relatedResources;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ResourceDetailVO)) return false;
        final ResourceDetailVO other = (ResourceDetailVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$categoryId = this.getCategoryId();
        final java.lang.Object other$categoryId = other.getCategoryId();
        if (this$categoryId == null ? other$categoryId != null : !this$categoryId.equals(other$categoryId)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$slug = this.getSlug();
        final java.lang.Object other$slug = other.getSlug();
        if (this$slug == null ? other$slug != null : !this$slug.equals(other$slug)) return false;
        final java.lang.Object this$categoryName = this.getCategoryName();
        final java.lang.Object other$categoryName = other.getCategoryName();
        if (this$categoryName == null ? other$categoryName != null : !this$categoryName.equals(other$categoryName)) return false;
        final java.lang.Object this$summary = this.getSummary();
        final java.lang.Object other$summary = other.getSummary();
        if (this$summary == null ? other$summary != null : !this$summary.equals(other$summary)) return false;
        final java.lang.Object this$coverImage = this.getCoverImage();
        final java.lang.Object other$coverImage = other.getCoverImage();
        if (this$coverImage == null ? other$coverImage != null : !this$coverImage.equals(other$coverImage)) return false;
        final java.lang.Object this$displayPrice = this.getDisplayPrice();
        final java.lang.Object other$displayPrice = other.getDisplayPrice();
        if (this$displayPrice == null ? other$displayPrice != null : !this$displayPrice.equals(other$displayPrice)) return false;
        final java.lang.Object this$grade = this.getGrade();
        final java.lang.Object other$grade = other.getGrade();
        if (this$grade == null ? other$grade != null : !this$grade.equals(other$grade)) return false;
        final java.lang.Object this$scene = this.getScene();
        final java.lang.Object other$scene = other.getScene();
        if (this$scene == null ? other$scene != null : !this$scene.equals(other$scene)) return false;
        final java.lang.Object this$previewImages = this.getPreviewImages();
        final java.lang.Object other$previewImages = other.getPreviewImages();
        if (this$previewImages == null ? other$previewImages != null : !this$previewImages.equals(other$previewImages)) return false;
        final java.lang.Object this$tags = this.getTags();
        final java.lang.Object other$tags = other.getTags();
        if (this$tags == null ? other$tags != null : !this$tags.equals(other$tags)) return false;
        final java.lang.Object this$publishTime = this.getPublishTime();
        final java.lang.Object other$publishTime = other.getPublishTime();
        if (this$publishTime == null ? other$publishTime != null : !this$publishTime.equals(other$publishTime)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        final java.lang.Object this$contentItems = this.getContentItems();
        final java.lang.Object other$contentItems = other.getContentItems();
        if (this$contentItems == null ? other$contentItems != null : !this$contentItems.equals(other$contentItems)) return false;
        final java.lang.Object this$descriptionHtml = this.getDescriptionHtml();
        final java.lang.Object other$descriptionHtml = other.getDescriptionHtml();
        if (this$descriptionHtml == null ? other$descriptionHtml != null : !this$descriptionHtml.equals(other$descriptionHtml)) return false;
        final java.lang.Object this$usageNotice = this.getUsageNotice();
        final java.lang.Object other$usageNotice = other.getUsageNotice();
        if (this$usageNotice == null ? other$usageNotice != null : !this$usageNotice.equals(other$usageNotice)) return false;
        final java.lang.Object this$faqList = this.getFaqList();
        final java.lang.Object other$faqList = other.getFaqList();
        if (this$faqList == null ? other$faqList != null : !this$faqList.equals(other$faqList)) return false;
        final java.lang.Object this$wechatConsult = this.getWechatConsult();
        final java.lang.Object other$wechatConsult = other.getWechatConsult();
        if (this$wechatConsult == null ? other$wechatConsult != null : !this$wechatConsult.equals(other$wechatConsult)) return false;
        final java.lang.Object this$relatedResources = this.getRelatedResources();
        final java.lang.Object other$relatedResources = other.getRelatedResources();
        if (this$relatedResources == null ? other$relatedResources != null : !this$relatedResources.equals(other$relatedResources)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ResourceDetailVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $categoryId = this.getCategoryId();
        result = result * PRIME + ($categoryId == null ? 43 : $categoryId.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $slug = this.getSlug();
        result = result * PRIME + ($slug == null ? 43 : $slug.hashCode());
        final java.lang.Object $categoryName = this.getCategoryName();
        result = result * PRIME + ($categoryName == null ? 43 : $categoryName.hashCode());
        final java.lang.Object $summary = this.getSummary();
        result = result * PRIME + ($summary == null ? 43 : $summary.hashCode());
        final java.lang.Object $coverImage = this.getCoverImage();
        result = result * PRIME + ($coverImage == null ? 43 : $coverImage.hashCode());
        final java.lang.Object $displayPrice = this.getDisplayPrice();
        result = result * PRIME + ($displayPrice == null ? 43 : $displayPrice.hashCode());
        final java.lang.Object $grade = this.getGrade();
        result = result * PRIME + ($grade == null ? 43 : $grade.hashCode());
        final java.lang.Object $scene = this.getScene();
        result = result * PRIME + ($scene == null ? 43 : $scene.hashCode());
        final java.lang.Object $previewImages = this.getPreviewImages();
        result = result * PRIME + ($previewImages == null ? 43 : $previewImages.hashCode());
        final java.lang.Object $tags = this.getTags();
        result = result * PRIME + ($tags == null ? 43 : $tags.hashCode());
        final java.lang.Object $publishTime = this.getPublishTime();
        result = result * PRIME + ($publishTime == null ? 43 : $publishTime.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        final java.lang.Object $contentItems = this.getContentItems();
        result = result * PRIME + ($contentItems == null ? 43 : $contentItems.hashCode());
        final java.lang.Object $descriptionHtml = this.getDescriptionHtml();
        result = result * PRIME + ($descriptionHtml == null ? 43 : $descriptionHtml.hashCode());
        final java.lang.Object $usageNotice = this.getUsageNotice();
        result = result * PRIME + ($usageNotice == null ? 43 : $usageNotice.hashCode());
        final java.lang.Object $faqList = this.getFaqList();
        result = result * PRIME + ($faqList == null ? 43 : $faqList.hashCode());
        final java.lang.Object $wechatConsult = this.getWechatConsult();
        result = result * PRIME + ($wechatConsult == null ? 43 : $wechatConsult.hashCode());
        final java.lang.Object $relatedResources = this.getRelatedResources();
        result = result * PRIME + ($relatedResources == null ? 43 : $relatedResources.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ResourceDetailVO(id=" + this.getId() + ", title=" + this.getTitle() + ", slug=" + this.getSlug() + ", categoryId=" + this.getCategoryId() + ", categoryName=" + this.getCategoryName() + ", summary=" + this.getSummary() + ", coverImage=" + this.getCoverImage() + ", displayPrice=" + this.getDisplayPrice() + ", grade=" + this.getGrade() + ", scene=" + this.getScene() + ", previewImages=" + this.getPreviewImages() + ", tags=" + this.getTags() + ", publishTime=" + this.getPublishTime() + ", updatedAt=" + this.getUpdatedAt() + ", contentItems=" + this.getContentItems() + ", descriptionHtml=" + this.getDescriptionHtml() + ", usageNotice=" + this.getUsageNotice() + ", faqList=" + this.getFaqList() + ", wechatConsult=" + this.getWechatConsult() + ", relatedResources=" + this.getRelatedResources() + ")";
    }
}
