// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.vo;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

public class ResourceAdminDetailVO {
    private Long id;
    private String title;
    private String slug;
    private Long categoryId;
    private String summary;
    private String coverImage;
    private BigDecimal displayPrice;
    private String grade;
    private String scene;
    private List<String> contentItems;
    private String descriptionHtml;
    private String usageNotice;
    private Integer status;
    private Integer isRecommended;
    private Integer viewCount;
    private Integer sortOrder;
    private LocalDateTime publishTime;
    private List<String> previewImageList;
    private List<Long> tagIdList;
    private List<Long> recommendedResourceIdList;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ResourceAdminDetailVO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSlug() {
        return this.slug;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCategoryId() {
        return this.categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSummary() {
        return this.summary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCoverImage() {
        return this.coverImage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDisplayPrice() {
        return this.displayPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGrade() {
        return this.grade;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getScene() {
        return this.scene;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getContentItems() {
        return this.contentItems;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescriptionHtml() {
        return this.descriptionHtml;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUsageNotice() {
        return this.usageNotice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getIsRecommended() {
        return this.isRecommended;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getViewCount() {
        return this.viewCount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getPublishTime() {
        return this.publishTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getPreviewImageList() {
        return this.previewImageList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<Long> getTagIdList() {
        return this.tagIdList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<Long> getRecommendedResourceIdList() {
        return this.recommendedResourceIdList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSlug(final String slug) {
        this.slug = slug;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategoryId(final Long categoryId) {
        this.categoryId = categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSummary(final String summary) {
        this.summary = summary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCoverImage(final String coverImage) {
        this.coverImage = coverImage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayPrice(final BigDecimal displayPrice) {
        this.displayPrice = displayPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGrade(final String grade) {
        this.grade = grade;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setScene(final String scene) {
        this.scene = scene;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContentItems(final List<String> contentItems) {
        this.contentItems = contentItems;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescriptionHtml(final String descriptionHtml) {
        this.descriptionHtml = descriptionHtml;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUsageNotice(final String usageNotice) {
        this.usageNotice = usageNotice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsRecommended(final Integer isRecommended) {
        this.isRecommended = isRecommended;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setViewCount(final Integer viewCount) {
        this.viewCount = viewCount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSortOrder(final Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPublishTime(final LocalDateTime publishTime) {
        this.publishTime = publishTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPreviewImageList(final List<String> previewImageList) {
        this.previewImageList = previewImageList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTagIdList(final List<Long> tagIdList) {
        this.tagIdList = tagIdList;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRecommendedResourceIdList(final List<Long> recommendedResourceIdList) {
        this.recommendedResourceIdList = recommendedResourceIdList;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ResourceAdminDetailVO)) return false;
        final ResourceAdminDetailVO other = (ResourceAdminDetailVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$categoryId = this.getCategoryId();
        final java.lang.Object other$categoryId = other.getCategoryId();
        if (this$categoryId == null ? other$categoryId != null : !this$categoryId.equals(other$categoryId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$isRecommended = this.getIsRecommended();
        final java.lang.Object other$isRecommended = other.getIsRecommended();
        if (this$isRecommended == null ? other$isRecommended != null : !this$isRecommended.equals(other$isRecommended)) return false;
        final java.lang.Object this$viewCount = this.getViewCount();
        final java.lang.Object other$viewCount = other.getViewCount();
        if (this$viewCount == null ? other$viewCount != null : !this$viewCount.equals(other$viewCount)) return false;
        final java.lang.Object this$sortOrder = this.getSortOrder();
        final java.lang.Object other$sortOrder = other.getSortOrder();
        if (this$sortOrder == null ? other$sortOrder != null : !this$sortOrder.equals(other$sortOrder)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$slug = this.getSlug();
        final java.lang.Object other$slug = other.getSlug();
        if (this$slug == null ? other$slug != null : !this$slug.equals(other$slug)) return false;
        final java.lang.Object this$summary = this.getSummary();
        final java.lang.Object other$summary = other.getSummary();
        if (this$summary == null ? other$summary != null : !this$summary.equals(other$summary)) return false;
        final java.lang.Object this$coverImage = this.getCoverImage();
        final java.lang.Object other$coverImage = other.getCoverImage();
        if (this$coverImage == null ? other$coverImage != null : !this$coverImage.equals(other$coverImage)) return false;
        final java.lang.Object this$displayPrice = this.getDisplayPrice();
        final java.lang.Object other$displayPrice = other.getDisplayPrice();
        if (this$displayPrice == null ? other$displayPrice != null : !this$displayPrice.equals(other$displayPrice)) return false;
        final java.lang.Object this$grade = this.getGrade();
        final java.lang.Object other$grade = other.getGrade();
        if (this$grade == null ? other$grade != null : !this$grade.equals(other$grade)) return false;
        final java.lang.Object this$scene = this.getScene();
        final java.lang.Object other$scene = other.getScene();
        if (this$scene == null ? other$scene != null : !this$scene.equals(other$scene)) return false;
        final java.lang.Object this$contentItems = this.getContentItems();
        final java.lang.Object other$contentItems = other.getContentItems();
        if (this$contentItems == null ? other$contentItems != null : !this$contentItems.equals(other$contentItems)) return false;
        final java.lang.Object this$descriptionHtml = this.getDescriptionHtml();
        final java.lang.Object other$descriptionHtml = other.getDescriptionHtml();
        if (this$descriptionHtml == null ? other$descriptionHtml != null : !this$descriptionHtml.equals(other$descriptionHtml)) return false;
        final java.lang.Object this$usageNotice = this.getUsageNotice();
        final java.lang.Object other$usageNotice = other.getUsageNotice();
        if (this$usageNotice == null ? other$usageNotice != null : !this$usageNotice.equals(other$usageNotice)) return false;
        final java.lang.Object this$publishTime = this.getPublishTime();
        final java.lang.Object other$publishTime = other.getPublishTime();
        if (this$publishTime == null ? other$publishTime != null : !this$publishTime.equals(other$publishTime)) return false;
        final java.lang.Object this$previewImageList = this.getPreviewImageList();
        final java.lang.Object other$previewImageList = other.getPreviewImageList();
        if (this$previewImageList == null ? other$previewImageList != null : !this$previewImageList.equals(other$previewImageList)) return false;
        final java.lang.Object this$tagIdList = this.getTagIdList();
        final java.lang.Object other$tagIdList = other.getTagIdList();
        if (this$tagIdList == null ? other$tagIdList != null : !this$tagIdList.equals(other$tagIdList)) return false;
        final java.lang.Object this$recommendedResourceIdList = this.getRecommendedResourceIdList();
        final java.lang.Object other$recommendedResourceIdList = other.getRecommendedResourceIdList();
        if (this$recommendedResourceIdList == null ? other$recommendedResourceIdList != null : !this$recommendedResourceIdList.equals(other$recommendedResourceIdList)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ResourceAdminDetailVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $categoryId = this.getCategoryId();
        result = result * PRIME + ($categoryId == null ? 43 : $categoryId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $isRecommended = this.getIsRecommended();
        result = result * PRIME + ($isRecommended == null ? 43 : $isRecommended.hashCode());
        final java.lang.Object $viewCount = this.getViewCount();
        result = result * PRIME + ($viewCount == null ? 43 : $viewCount.hashCode());
        final java.lang.Object $sortOrder = this.getSortOrder();
        result = result * PRIME + ($sortOrder == null ? 43 : $sortOrder.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $slug = this.getSlug();
        result = result * PRIME + ($slug == null ? 43 : $slug.hashCode());
        final java.lang.Object $summary = this.getSummary();
        result = result * PRIME + ($summary == null ? 43 : $summary.hashCode());
        final java.lang.Object $coverImage = this.getCoverImage();
        result = result * PRIME + ($coverImage == null ? 43 : $coverImage.hashCode());
        final java.lang.Object $displayPrice = this.getDisplayPrice();
        result = result * PRIME + ($displayPrice == null ? 43 : $displayPrice.hashCode());
        final java.lang.Object $grade = this.getGrade();
        result = result * PRIME + ($grade == null ? 43 : $grade.hashCode());
        final java.lang.Object $scene = this.getScene();
        result = result * PRIME + ($scene == null ? 43 : $scene.hashCode());
        final java.lang.Object $contentItems = this.getContentItems();
        result = result * PRIME + ($contentItems == null ? 43 : $contentItems.hashCode());
        final java.lang.Object $descriptionHtml = this.getDescriptionHtml();
        result = result * PRIME + ($descriptionHtml == null ? 43 : $descriptionHtml.hashCode());
        final java.lang.Object $usageNotice = this.getUsageNotice();
        result = result * PRIME + ($usageNotice == null ? 43 : $usageNotice.hashCode());
        final java.lang.Object $publishTime = this.getPublishTime();
        result = result * PRIME + ($publishTime == null ? 43 : $publishTime.hashCode());
        final java.lang.Object $previewImageList = this.getPreviewImageList();
        result = result * PRIME + ($previewImageList == null ? 43 : $previewImageList.hashCode());
        final java.lang.Object $tagIdList = this.getTagIdList();
        result = result * PRIME + ($tagIdList == null ? 43 : $tagIdList.hashCode());
        final java.lang.Object $recommendedResourceIdList = this.getRecommendedResourceIdList();
        result = result * PRIME + ($recommendedResourceIdList == null ? 43 : $recommendedResourceIdList.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ResourceAdminDetailVO(id=" + this.getId() + ", title=" + this.getTitle() + ", slug=" + this.getSlug() + ", categoryId=" + this.getCategoryId() + ", summary=" + this.getSummary() + ", coverImage=" + this.getCoverImage() + ", displayPrice=" + this.getDisplayPrice() + ", grade=" + this.getGrade() + ", scene=" + this.getScene() + ", contentItems=" + this.getContentItems() + ", descriptionHtml=" + this.getDescriptionHtml() + ", usageNotice=" + this.getUsageNotice() + ", status=" + this.getStatus() + ", isRecommended=" + this.getIsRecommended() + ", viewCount=" + this.getViewCount() + ", sortOrder=" + this.getSortOrder() + ", publishTime=" + this.getPublishTime() + ", previewImageList=" + this.getPreviewImageList() + ", tagIdList=" + this.getTagIdList() + ", recommendedResourceIdList=" + this.getRecommendedResourceIdList() + ")";
    }
}
