// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.vo;

public class WechatConsultVO {
    private String wechatId;
    private String wechatQrUrl;
    private String wechatTip;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WechatConsultVO() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWechatId() {
        return this.wechatId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWechatQrUrl() {
        return this.wechatQrUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWechatTip() {
        return this.wechatTip;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWechatId(final String wechatId) {
        this.wechatId = wechatId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWechatQrUrl(final String wechatQrUrl) {
        this.wechatQrUrl = wechatQrUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWechatTip(final String wechatTip) {
        this.wechatTip = wechatTip;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof WechatConsultVO)) return false;
        final WechatConsultVO other = (WechatConsultVO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$wechatId = this.getWechatId();
        final java.lang.Object other$wechatId = other.getWechatId();
        if (this$wechatId == null ? other$wechatId != null : !this$wechatId.equals(other$wechatId)) return false;
        final java.lang.Object this$wechatQrUrl = this.getWechatQrUrl();
        final java.lang.Object other$wechatQrUrl = other.getWechatQrUrl();
        if (this$wechatQrUrl == null ? other$wechatQrUrl != null : !this$wechatQrUrl.equals(other$wechatQrUrl)) return false;
        final java.lang.Object this$wechatTip = this.getWechatTip();
        final java.lang.Object other$wechatTip = other.getWechatTip();
        if (this$wechatTip == null ? other$wechatTip != null : !this$wechatTip.equals(other$wechatTip)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof WechatConsultVO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $wechatId = this.getWechatId();
        result = result * PRIME + ($wechatId == null ? 43 : $wechatId.hashCode());
        final java.lang.Object $wechatQrUrl = this.getWechatQrUrl();
        result = result * PRIME + ($wechatQrUrl == null ? 43 : $wechatQrUrl.hashCode());
        final java.lang.Object $wechatTip = this.getWechatTip();
        result = result * PRIME + ($wechatTip == null ? 43 : $wechatTip.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "WechatConsultVO(wechatId=" + this.getWechatId() + ", wechatQrUrl=" + this.getWechatQrUrl() + ", wechatTip=" + this.getWechatTip() + ")";
    }
}
