// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public class FaqSaveRequest {
    @NotBlank(message = "问题不能为空")
    @Size(max = 255, message = "问题长度不能超过255个字符")
    private String question;
    @NotBlank(message = "回答不能为空")
    private String answer;
    @NotNull(message = "排序值不能为空")
    private Integer sortOrder;
    @NotNull(message = "状态不能为空")
    private Integer status;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public FaqSaveRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getQuestion() {
        return this.question;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAnswer() {
        return this.answer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setQuestion(final String question) {
        this.question = question;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAnswer(final String answer) {
        this.answer = answer;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSortOrder(final Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof FaqSaveRequest)) return false;
        final FaqSaveRequest other = (FaqSaveRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$sortOrder = this.getSortOrder();
        final java.lang.Object other$sortOrder = other.getSortOrder();
        if (this$sortOrder == null ? other$sortOrder != null : !this$sortOrder.equals(other$sortOrder)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$question = this.getQuestion();
        final java.lang.Object other$question = other.getQuestion();
        if (this$question == null ? other$question != null : !this$question.equals(other$question)) return false;
        final java.lang.Object this$answer = this.getAnswer();
        final java.lang.Object other$answer = other.getAnswer();
        if (this$answer == null ? other$answer != null : !this$answer.equals(other$answer)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof FaqSaveRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $sortOrder = this.getSortOrder();
        result = result * PRIME + ($sortOrder == null ? 43 : $sortOrder.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $question = this.getQuestion();
        result = result * PRIME + ($question == null ? 43 : $question.hashCode());
        final java.lang.Object $answer = this.getAnswer();
        result = result * PRIME + ($answer == null ? 43 : $answer.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "FaqSaveRequest(question=" + this.getQuestion() + ", answer=" + this.getAnswer() + ", sortOrder=" + this.getSortOrder() + ", status=" + this.getStatus() + ")";
    }
}
