// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class LeadCreateRequest {
    @NotBlank(message = "老师称呼不能为空")
    @Size(max = 50, message = "老师称呼长度不能超过50个字符")
    private String name;
    @NotBlank(message = "联系方式不能为空")
    @Size(max = 100, message = "联系方式长度不能超过100个字符")
    private String contact;
    @NotBlank(message = "来源页面不能为空")
    @Size(max = 120, message = "来源页面长度不能超过120个字符")
    private String sourcePage;
    @Size(max = 1000, message = "咨询内容长度不能超过1000个字符")
    private String message;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LeadCreateRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContact() {
        return this.contact;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSourcePage() {
        return this.sourcePage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContact(final String contact) {
        this.contact = contact;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSourcePage(final String sourcePage) {
        this.sourcePage = sourcePage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LeadCreateRequest)) return false;
        final LeadCreateRequest other = (LeadCreateRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$contact = this.getContact();
        final java.lang.Object other$contact = other.getContact();
        if (this$contact == null ? other$contact != null : !this$contact.equals(other$contact)) return false;
        final java.lang.Object this$sourcePage = this.getSourcePage();
        final java.lang.Object other$sourcePage = other.getSourcePage();
        if (this$sourcePage == null ? other$sourcePage != null : !this$sourcePage.equals(other$sourcePage)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LeadCreateRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $contact = this.getContact();
        result = result * PRIME + ($contact == null ? 43 : $contact.hashCode());
        final java.lang.Object $sourcePage = this.getSourcePage();
        result = result * PRIME + ($sourcePage == null ? 43 : $sourcePage.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "LeadCreateRequest(name=" + this.getName() + ", contact=" + this.getContact() + ", sourcePage=" + this.getSourcePage() + ", message=" + this.getMessage() + ")";
    }
}
