// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.dto;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public class LeadStatusUpdateRequest {
    @NotNull(message = "线索状态不能为空")
    private Integer status;
    @Size(max = 1000, message = "跟进备注长度不能超过1000个字符")
    private String followUpNote;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LeadStatusUpdateRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFollowUpNote() {
        return this.followUpNote;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFollowUpNote(final String followUpNote) {
        this.followUpNote = followUpNote;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LeadStatusUpdateRequest)) return false;
        final LeadStatusUpdateRequest other = (LeadStatusUpdateRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$followUpNote = this.getFollowUpNote();
        final java.lang.Object other$followUpNote = other.getFollowUpNote();
        if (this$followUpNote == null ? other$followUpNote != null : !this$followUpNote.equals(other$followUpNote)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LeadStatusUpdateRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $followUpNote = this.getFollowUpNote();
        result = result * PRIME + ($followUpNote == null ? 43 : $followUpNote.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "LeadStatusUpdateRequest(status=" + this.getStatus() + ", followUpNote=" + this.getFollowUpNote() + ")";
    }
}
