// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class PageContentSaveRequest {
    @NotBlank(message = "页面标题不能为空")
    @Size(max = 100, message = "页面标题长度不能超过100个字符")
    private String title;
    @NotBlank(message = "页面内容不能为空")
    private String contentHtml;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PageContentSaveRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContentHtml() {
        return this.contentHtml;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContentHtml(final String contentHtml) {
        this.contentHtml = contentHtml;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PageContentSaveRequest)) return false;
        final PageContentSaveRequest other = (PageContentSaveRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$contentHtml = this.getContentHtml();
        final java.lang.Object other$contentHtml = other.getContentHtml();
        if (this$contentHtml == null ? other$contentHtml != null : !this$contentHtml.equals(other$contentHtml)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PageContentSaveRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $contentHtml = this.getContentHtml();
        result = result * PRIME + ($contentHtml == null ? 43 : $contentHtml.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PageContentSaveRequest(title=" + this.getTitle() + ", contentHtml=" + this.getContentHtml() + ")";
    }
}
