// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.dto;

import com.teacherresourcehub.common.api.PageRequest;

public class ResourceQueryRequest extends PageRequest {
    private Long categoryId;
    private Long tagId;
    private String grade;
    private String scene;
    private String keyword;
    private String sortType = "latest";

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ResourceQueryRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCategoryId() {
        return this.categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getTagId() {
        return this.tagId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGrade() {
        return this.grade;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getScene() {
        return this.scene;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getKeyword() {
        return this.keyword;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSortType() {
        return this.sortType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategoryId(final Long categoryId) {
        this.categoryId = categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTagId(final Long tagId) {
        this.tagId = tagId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGrade(final String grade) {
        this.grade = grade;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setScene(final String scene) {
        this.scene = scene;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setKeyword(final String keyword) {
        this.keyword = keyword;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSortType(final String sortType) {
        this.sortType = sortType;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ResourceQueryRequest(categoryId=" + this.getCategoryId() + ", tagId=" + this.getTagId() + ", grade=" + this.getGrade() + ", scene=" + this.getScene() + ", keyword=" + this.getKeyword() + ", sortType=" + this.getSortType() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ResourceQueryRequest)) return false;
        final ResourceQueryRequest other = (ResourceQueryRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$categoryId = this.getCategoryId();
        final java.lang.Object other$categoryId = other.getCategoryId();
        if (this$categoryId == null ? other$categoryId != null : !this$categoryId.equals(other$categoryId)) return false;
        final java.lang.Object this$tagId = this.getTagId();
        final java.lang.Object other$tagId = other.getTagId();
        if (this$tagId == null ? other$tagId != null : !this$tagId.equals(other$tagId)) return false;
        final java.lang.Object this$grade = this.getGrade();
        final java.lang.Object other$grade = other.getGrade();
        if (this$grade == null ? other$grade != null : !this$grade.equals(other$grade)) return false;
        final java.lang.Object this$scene = this.getScene();
        final java.lang.Object other$scene = other.getScene();
        if (this$scene == null ? other$scene != null : !this$scene.equals(other$scene)) return false;
        final java.lang.Object this$keyword = this.getKeyword();
        final java.lang.Object other$keyword = other.getKeyword();
        if (this$keyword == null ? other$keyword != null : !this$keyword.equals(other$keyword)) return false;
        final java.lang.Object this$sortType = this.getSortType();
        final java.lang.Object other$sortType = other.getSortType();
        if (this$sortType == null ? other$sortType != null : !this$sortType.equals(other$sortType)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ResourceQueryRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $categoryId = this.getCategoryId();
        result = result * PRIME + ($categoryId == null ? 43 : $categoryId.hashCode());
        final java.lang.Object $tagId = this.getTagId();
        result = result * PRIME + ($tagId == null ? 43 : $tagId.hashCode());
        final java.lang.Object $grade = this.getGrade();
        result = result * PRIME + ($grade == null ? 43 : $grade.hashCode());
        final java.lang.Object $scene = this.getScene();
        result = result * PRIME + ($scene == null ? 43 : $scene.hashCode());
        final java.lang.Object $keyword = this.getKeyword();
        result = result * PRIME + ($keyword == null ? 43 : $keyword.hashCode());
        final java.lang.Object $sortType = this.getSortType();
        result = result * PRIME + ($sortType == null ? 43 : $sortType.hashCode());
        return result;
    }
}
