// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.dto;

import jakarta.validation.constraints.NotBlank;

public class SiteConfigSaveRequest {
    @NotBlank(message = "站点名称不能为空")
    private String siteName;
    @NotBlank(message = "SEO标题不能为空")
    private String seoTitle;
    @NotBlank(message = "SEO关键词不能为空")
    private String seoKeywords;
    @NotBlank(message = "SEO描述不能为空")
    private String seoDescription;
    private String contactPhone;
    private String contactWechat;
    private String contactEmail;
    private String footerText;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public SiteConfigSaveRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSiteName() {
        return this.siteName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSeoTitle() {
        return this.seoTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSeoKeywords() {
        return this.seoKeywords;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSeoDescription() {
        return this.seoDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContactPhone() {
        return this.contactPhone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContactWechat() {
        return this.contactWechat;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContactEmail() {
        return this.contactEmail;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFooterText() {
        return this.footerText;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSiteName(final String siteName) {
        this.siteName = siteName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSeoTitle(final String seoTitle) {
        this.seoTitle = seoTitle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSeoKeywords(final String seoKeywords) {
        this.seoKeywords = seoKeywords;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSeoDescription(final String seoDescription) {
        this.seoDescription = seoDescription;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContactPhone(final String contactPhone) {
        this.contactPhone = contactPhone;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContactWechat(final String contactWechat) {
        this.contactWechat = contactWechat;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContactEmail(final String contactEmail) {
        this.contactEmail = contactEmail;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFooterText(final String footerText) {
        this.footerText = footerText;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SiteConfigSaveRequest)) return false;
        final SiteConfigSaveRequest other = (SiteConfigSaveRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$siteName = this.getSiteName();
        final java.lang.Object other$siteName = other.getSiteName();
        if (this$siteName == null ? other$siteName != null : !this$siteName.equals(other$siteName)) return false;
        final java.lang.Object this$seoTitle = this.getSeoTitle();
        final java.lang.Object other$seoTitle = other.getSeoTitle();
        if (this$seoTitle == null ? other$seoTitle != null : !this$seoTitle.equals(other$seoTitle)) return false;
        final java.lang.Object this$seoKeywords = this.getSeoKeywords();
        final java.lang.Object other$seoKeywords = other.getSeoKeywords();
        if (this$seoKeywords == null ? other$seoKeywords != null : !this$seoKeywords.equals(other$seoKeywords)) return false;
        final java.lang.Object this$seoDescription = this.getSeoDescription();
        final java.lang.Object other$seoDescription = other.getSeoDescription();
        if (this$seoDescription == null ? other$seoDescription != null : !this$seoDescription.equals(other$seoDescription)) return false;
        final java.lang.Object this$contactPhone = this.getContactPhone();
        final java.lang.Object other$contactPhone = other.getContactPhone();
        if (this$contactPhone == null ? other$contactPhone != null : !this$contactPhone.equals(other$contactPhone)) return false;
        final java.lang.Object this$contactWechat = this.getContactWechat();
        final java.lang.Object other$contactWechat = other.getContactWechat();
        if (this$contactWechat == null ? other$contactWechat != null : !this$contactWechat.equals(other$contactWechat)) return false;
        final java.lang.Object this$contactEmail = this.getContactEmail();
        final java.lang.Object other$contactEmail = other.getContactEmail();
        if (this$contactEmail == null ? other$contactEmail != null : !this$contactEmail.equals(other$contactEmail)) return false;
        final java.lang.Object this$footerText = this.getFooterText();
        final java.lang.Object other$footerText = other.getFooterText();
        if (this$footerText == null ? other$footerText != null : !this$footerText.equals(other$footerText)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SiteConfigSaveRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $siteName = this.getSiteName();
        result = result * PRIME + ($siteName == null ? 43 : $siteName.hashCode());
        final java.lang.Object $seoTitle = this.getSeoTitle();
        result = result * PRIME + ($seoTitle == null ? 43 : $seoTitle.hashCode());
        final java.lang.Object $seoKeywords = this.getSeoKeywords();
        result = result * PRIME + ($seoKeywords == null ? 43 : $seoKeywords.hashCode());
        final java.lang.Object $seoDescription = this.getSeoDescription();
        result = result * PRIME + ($seoDescription == null ? 43 : $seoDescription.hashCode());
        final java.lang.Object $contactPhone = this.getContactPhone();
        result = result * PRIME + ($contactPhone == null ? 43 : $contactPhone.hashCode());
        final java.lang.Object $contactWechat = this.getContactWechat();
        result = result * PRIME + ($contactWechat == null ? 43 : $contactWechat.hashCode());
        final java.lang.Object $contactEmail = this.getContactEmail();
        result = result * PRIME + ($contactEmail == null ? 43 : $contactEmail.hashCode());
        final java.lang.Object $footerText = this.getFooterText();
        result = result * PRIME + ($footerText == null ? 43 : $footerText.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "SiteConfigSaveRequest(siteName=" + this.getSiteName() + ", seoTitle=" + this.getSeoTitle() + ", seoKeywords=" + this.getSeoKeywords() + ", seoDescription=" + this.getSeoDescription() + ", contactPhone=" + this.getContactPhone() + ", contactWechat=" + this.getContactWechat() + ", contactEmail=" + this.getContactEmail() + ", footerText=" + this.getFooterText() + ")";
    }
}
