// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.common.enums;

public enum CommonStatus {
    DISABLED(0, "禁用"), ENABLED(1, "启用");
    private final int code;
    private final String description;

    CommonStatus(int code, String description) {
        this.code = code;
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }
}
