// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.common.enums;

public enum LeadStatus {
    PENDING(0, "待跟进"), CONTACTED(1, "已联系"), DEAL(2, "已成交"), CLOSED(3, "已关闭");
    private final int code;
    private final String description;

    LeadStatus(int code, String description) {
        this.code = code;
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }
}
