// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.common.enums;

import java.util.Arrays;

public enum ResourceSortType {
    LATEST("latest", "最新"), HOT("hot", "热门"), RECOMMENDED("recommended", "推荐");
    private final String value;
    private final String description;

    ResourceSortType(String value, String description) {
        this.value = value;
        this.description = description;
    }

    public static ResourceSortType fromValue(String value) {
        if (value == null || value.isBlank()) {
            return LATEST;
        }
        return Arrays.stream(values()).filter(item -> item.value.equalsIgnoreCase(value)).findFirst().orElse(LATEST);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getValue() {
        return this.value;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }
}
