// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.common.enums;

public enum ResourceStatus {
    OFFLINE(0, "下线"), PUBLISHED(1, "已发布");
    private final int code;
    private final String description;

    ResourceStatus(int code, String description) {
        this.code = code;
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }
}
