// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.exception;

public class BusinessException extends RuntimeException {
    private final Integer code;

    public BusinessException(String message) {
        super(message);
        this.code = -1;
    }

    public BusinessException(Integer code, String message) {
        super(message);
        this.code = code;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getCode() {
        return this.code;
    }
}
