// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@TableName("resource")
public class Resource {
    @TableId(type = IdType.AUTO)
    private Long id;
    private String title;
    private String slug;
    private Long categoryId;
    private String summary;
    private String coverImage;
    private BigDecimal displayPrice;
    private String grade;
    private String scene;
    @TableField("content_items_json")
    private String contentItemsJson;
    private String descriptionHtml;
    private String usageNotice;
    private Integer status;
    private Integer isRecommended;
    private Integer viewCount;
    private Integer sortOrder;
    private LocalDateTime publishTime;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    @TableLogic
    private Integer isDeleted;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Resource() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSlug() {
        return this.slug;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getCategoryId() {
        return this.categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSummary() {
        return this.summary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCoverImage() {
        return this.coverImage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getDisplayPrice() {
        return this.displayPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGrade() {
        return this.grade;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getScene() {
        return this.scene;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getContentItemsJson() {
        return this.contentItemsJson;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescriptionHtml() {
        return this.descriptionHtml;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUsageNotice() {
        return this.usageNotice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getIsRecommended() {
        return this.isRecommended;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getViewCount() {
        return this.viewCount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getPublishTime() {
        return this.publishTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSlug(final String slug) {
        this.slug = slug;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCategoryId(final Long categoryId) {
        this.categoryId = categoryId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSummary(final String summary) {
        this.summary = summary;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCoverImage(final String coverImage) {
        this.coverImage = coverImage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayPrice(final BigDecimal displayPrice) {
        this.displayPrice = displayPrice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGrade(final String grade) {
        this.grade = grade;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setScene(final String scene) {
        this.scene = scene;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setContentItemsJson(final String contentItemsJson) {
        this.contentItemsJson = contentItemsJson;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescriptionHtml(final String descriptionHtml) {
        this.descriptionHtml = descriptionHtml;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUsageNotice(final String usageNotice) {
        this.usageNotice = usageNotice;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsRecommended(final Integer isRecommended) {
        this.isRecommended = isRecommended;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setViewCount(final Integer viewCount) {
        this.viewCount = viewCount;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSortOrder(final Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPublishTime(final LocalDateTime publishTime) {
        this.publishTime = publishTime;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsDeleted(final Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Resource)) return false;
        final Resource other = (Resource) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$categoryId = this.getCategoryId();
        final java.lang.Object other$categoryId = other.getCategoryId();
        if (this$categoryId == null ? other$categoryId != null : !this$categoryId.equals(other$categoryId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$isRecommended = this.getIsRecommended();
        final java.lang.Object other$isRecommended = other.getIsRecommended();
        if (this$isRecommended == null ? other$isRecommended != null : !this$isRecommended.equals(other$isRecommended)) return false;
        final java.lang.Object this$viewCount = this.getViewCount();
        final java.lang.Object other$viewCount = other.getViewCount();
        if (this$viewCount == null ? other$viewCount != null : !this$viewCount.equals(other$viewCount)) return false;
        final java.lang.Object this$sortOrder = this.getSortOrder();
        final java.lang.Object other$sortOrder = other.getSortOrder();
        if (this$sortOrder == null ? other$sortOrder != null : !this$sortOrder.equals(other$sortOrder)) return false;
        final java.lang.Object this$isDeleted = this.getIsDeleted();
        final java.lang.Object other$isDeleted = other.getIsDeleted();
        if (this$isDeleted == null ? other$isDeleted != null : !this$isDeleted.equals(other$isDeleted)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$slug = this.getSlug();
        final java.lang.Object other$slug = other.getSlug();
        if (this$slug == null ? other$slug != null : !this$slug.equals(other$slug)) return false;
        final java.lang.Object this$summary = this.getSummary();
        final java.lang.Object other$summary = other.getSummary();
        if (this$summary == null ? other$summary != null : !this$summary.equals(other$summary)) return false;
        final java.lang.Object this$coverImage = this.getCoverImage();
        final java.lang.Object other$coverImage = other.getCoverImage();
        if (this$coverImage == null ? other$coverImage != null : !this$coverImage.equals(other$coverImage)) return false;
        final java.lang.Object this$displayPrice = this.getDisplayPrice();
        final java.lang.Object other$displayPrice = other.getDisplayPrice();
        if (this$displayPrice == null ? other$displayPrice != null : !this$displayPrice.equals(other$displayPrice)) return false;
        final java.lang.Object this$grade = this.getGrade();
        final java.lang.Object other$grade = other.getGrade();
        if (this$grade == null ? other$grade != null : !this$grade.equals(other$grade)) return false;
        final java.lang.Object this$scene = this.getScene();
        final java.lang.Object other$scene = other.getScene();
        if (this$scene == null ? other$scene != null : !this$scene.equals(other$scene)) return false;
        final java.lang.Object this$contentItemsJson = this.getContentItemsJson();
        final java.lang.Object other$contentItemsJson = other.getContentItemsJson();
        if (this$contentItemsJson == null ? other$contentItemsJson != null : !this$contentItemsJson.equals(other$contentItemsJson)) return false;
        final java.lang.Object this$descriptionHtml = this.getDescriptionHtml();
        final java.lang.Object other$descriptionHtml = other.getDescriptionHtml();
        if (this$descriptionHtml == null ? other$descriptionHtml != null : !this$descriptionHtml.equals(other$descriptionHtml)) return false;
        final java.lang.Object this$usageNotice = this.getUsageNotice();
        final java.lang.Object other$usageNotice = other.getUsageNotice();
        if (this$usageNotice == null ? other$usageNotice != null : !this$usageNotice.equals(other$usageNotice)) return false;
        final java.lang.Object this$publishTime = this.getPublishTime();
        final java.lang.Object other$publishTime = other.getPublishTime();
        if (this$publishTime == null ? other$publishTime != null : !this$publishTime.equals(other$publishTime)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Resource;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $categoryId = this.getCategoryId();
        result = result * PRIME + ($categoryId == null ? 43 : $categoryId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $isRecommended = this.getIsRecommended();
        result = result * PRIME + ($isRecommended == null ? 43 : $isRecommended.hashCode());
        final java.lang.Object $viewCount = this.getViewCount();
        result = result * PRIME + ($viewCount == null ? 43 : $viewCount.hashCode());
        final java.lang.Object $sortOrder = this.getSortOrder();
        result = result * PRIME + ($sortOrder == null ? 43 : $sortOrder.hashCode());
        final java.lang.Object $isDeleted = this.getIsDeleted();
        result = result * PRIME + ($isDeleted == null ? 43 : $isDeleted.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $slug = this.getSlug();
        result = result * PRIME + ($slug == null ? 43 : $slug.hashCode());
        final java.lang.Object $summary = this.getSummary();
        result = result * PRIME + ($summary == null ? 43 : $summary.hashCode());
        final java.lang.Object $coverImage = this.getCoverImage();
        result = result * PRIME + ($coverImage == null ? 43 : $coverImage.hashCode());
        final java.lang.Object $displayPrice = this.getDisplayPrice();
        result = result * PRIME + ($displayPrice == null ? 43 : $displayPrice.hashCode());
        final java.lang.Object $grade = this.getGrade();
        result = result * PRIME + ($grade == null ? 43 : $grade.hashCode());
        final java.lang.Object $scene = this.getScene();
        result = result * PRIME + ($scene == null ? 43 : $scene.hashCode());
        final java.lang.Object $contentItemsJson = this.getContentItemsJson();
        result = result * PRIME + ($contentItemsJson == null ? 43 : $contentItemsJson.hashCode());
        final java.lang.Object $descriptionHtml = this.getDescriptionHtml();
        result = result * PRIME + ($descriptionHtml == null ? 43 : $descriptionHtml.hashCode());
        final java.lang.Object $usageNotice = this.getUsageNotice();
        result = result * PRIME + ($usageNotice == null ? 43 : $usageNotice.hashCode());
        final java.lang.Object $publishTime = this.getPublishTime();
        result = result * PRIME + ($publishTime == null ? 43 : $publishTime.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Resource(id=" + this.getId() + ", title=" + this.getTitle() + ", slug=" + this.getSlug() + ", categoryId=" + this.getCategoryId() + ", summary=" + this.getSummary() + ", coverImage=" + this.getCoverImage() + ", displayPrice=" + this.getDisplayPrice() + ", grade=" + this.getGrade() + ", scene=" + this.getScene() + ", contentItemsJson=" + this.getContentItemsJson() + ", descriptionHtml=" + this.getDescriptionHtml() + ", usageNotice=" + this.getUsageNotice() + ", status=" + this.getStatus() + ", isRecommended=" + this.getIsRecommended() + ", viewCount=" + this.getViewCount() + ", sortOrder=" + this.getSortOrder() + ", publishTime=" + this.getPublishTime() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ", isDeleted=" + this.getIsDeleted() + ")";
    }
}
