// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.common.api;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;

public class PageRequest {
    @Min(value = 1, message = "页码最小为1")
    private Long pageNum = 1L;
    @Min(value = 1, message = "每页条数最小为1")
    @Max(value = 100, message = "每页条数最大为100")
    private Long pageSize = 10L;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PageRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getPageNum() {
        return this.pageNum;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getPageSize() {
        return this.pageSize;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPageNum(final Long pageNum) {
        this.pageNum = pageNum;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPageSize(final Long pageSize) {
        this.pageSize = pageSize;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PageRequest)) return false;
        final PageRequest other = (PageRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$pageNum = this.getPageNum();
        final java.lang.Object other$pageNum = other.getPageNum();
        if (this$pageNum == null ? other$pageNum != null : !this$pageNum.equals(other$pageNum)) return false;
        final java.lang.Object this$pageSize = this.getPageSize();
        final java.lang.Object other$pageSize = other.getPageSize();
        if (this$pageSize == null ? other$pageSize != null : !this$pageSize.equals(other$pageSize)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PageRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $pageNum = this.getPageNum();
        result = result * PRIME + ($pageNum == null ? 43 : $pageNum.hashCode());
        final java.lang.Object $pageSize = this.getPageSize();
        result = result * PRIME + ($pageSize == null ? 43 : $pageSize.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PageRequest(pageNum=" + this.getPageNum() + ", pageSize=" + this.getPageSize() + ")";
    }
}
