// Generated by delombok at Tue Mar 31 15:04:14 CST 2026
package com.teacherresourcehub.common.api;

import java.util.Collections;
import java.util.List;

public class PageResult<T> {
    private Long pageNum;
    private Long pageSize;
    private Long total;
    private Long totalPage;
    private List<T> list;

    public PageResult(Long pageNum, Long pageSize, Long total, Long totalPage, List<T> list) {
        this.pageNum = pageNum;
        this.pageSize = pageSize;
        this.total = total;
        this.totalPage = totalPage;
        this.list = list;
    }

    public static <T> PageResult<T> of(Long pageNum, Long pageSize, Long total, List<T> list) {
        long totalPage = pageSize == null || pageSize <= 0 ? 0 : (total + pageSize - 1) / pageSize;
        return new PageResult<T>(pageNum, pageSize, total, totalPage, list == null ? Collections.emptyList() : list);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getPageNum() {
        return this.pageNum;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getPageSize() {
        return this.pageSize;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getTotal() {
        return this.total;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getTotalPage() {
        return this.totalPage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<T> getList() {
        return this.list;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPageNum(final Long pageNum) {
        this.pageNum = pageNum;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPageSize(final Long pageSize) {
        this.pageSize = pageSize;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotal(final Long total) {
        this.total = total;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalPage(final Long totalPage) {
        this.totalPage = totalPage;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setList(final List<T> list) {
        this.list = list;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PageResult)) return false;
        final PageResult<?> other = (PageResult<?>) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$pageNum = this.getPageNum();
        final java.lang.Object other$pageNum = other.getPageNum();
        if (this$pageNum == null ? other$pageNum != null : !this$pageNum.equals(other$pageNum)) return false;
        final java.lang.Object this$pageSize = this.getPageSize();
        final java.lang.Object other$pageSize = other.getPageSize();
        if (this$pageSize == null ? other$pageSize != null : !this$pageSize.equals(other$pageSize)) return false;
        final java.lang.Object this$total = this.getTotal();
        final java.lang.Object other$total = other.getTotal();
        if (this$total == null ? other$total != null : !this$total.equals(other$total)) return false;
        final java.lang.Object this$totalPage = this.getTotalPage();
        final java.lang.Object other$totalPage = other.getTotalPage();
        if (this$totalPage == null ? other$totalPage != null : !this$totalPage.equals(other$totalPage)) return false;
        final java.lang.Object this$list = this.getList();
        final java.lang.Object other$list = other.getList();
        if (this$list == null ? other$list != null : !this$list.equals(other$list)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PageResult;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $pageNum = this.getPageNum();
        result = result * PRIME + ($pageNum == null ? 43 : $pageNum.hashCode());
        final java.lang.Object $pageSize = this.getPageSize();
        result = result * PRIME + ($pageSize == null ? 43 : $pageSize.hashCode());
        final java.lang.Object $total = this.getTotal();
        result = result * PRIME + ($total == null ? 43 : $total.hashCode());
        final java.lang.Object $totalPage = this.getTotalPage();
        result = result * PRIME + ($totalPage == null ? 43 : $totalPage.hashCode());
        final java.lang.Object $list = this.getList();
        result = result * PRIME + ($list == null ? 43 : $list.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PageResult(pageNum=" + this.getPageNum() + ", pageSize=" + this.getPageSize() + ", total=" + this.getTotal() + ", totalPage=" + this.getTotalPage() + ", list=" + this.getList() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PageResult() {
    }
}
