SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS `teacher_resource_hub`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE `teacher_resource_hub`;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `resource_recommend`;
DROP TABLE IF EXISTS `resource_tag`;
DROP TABLE IF EXISTS `resource_preview`;
DROP TABLE IF EXISTS `lead`;
DROP TABLE IF EXISTS `faq`;
DROP TABLE IF EXISTS `site_config`;
DROP TABLE IF EXISTS `page_content`;
DROP TABLE IF EXISTS `resource`;
DROP TABLE IF EXISTS `tag`;
DROP TABLE IF EXISTS `category`;
DROP TABLE IF EXISTS `admin_user`;

CREATE TABLE `admin_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `username` VARCHAR(50) NOT NULL COMMENT '登录用户名',
  `password` VARCHAR(255) NOT NULL COMMENT 'BCrypt加密密码',
  `nickname` VARCHAR(50) NOT NULL COMMENT '管理员昵称',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0禁用 1启用',
  `last_login_time` DATETIME NULL DEFAULT NULL COMMENT '最后登录时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='后台管理员表';

CREATE TABLE `category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(50) NOT NULL COMMENT '分类名称',
  `slug` VARCHAR(100) NOT NULL COMMENT '分类别名',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '分类简介',
  `icon` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '分类图标URL',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序值，数值越大越靠前',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0禁用 1启用',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源分类表';

CREATE TABLE `tag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(50) NOT NULL COMMENT '标签名称',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序值，数值越大越靠前',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0禁用 1启用',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源标签表';

CREATE TABLE `resource` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `title` VARCHAR(150) NOT NULL COMMENT '资源标题',
  `slug` VARCHAR(180) NOT NULL COMMENT '资源别名',
  `category_id` BIGINT NOT NULL COMMENT '分类ID',
  `summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '资源简介',
  `cover_image` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '封面图URL',
  `display_price` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '展示价格',
  `grade` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '适用年级',
  `scene` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '适用场景',
  `content_items_json` TEXT NOT NULL COMMENT '资源包含内容清单JSON字符串，例如 ["课件PPT","配套教案","逐字稿"]',
  `description_html` LONGTEXT NOT NULL COMMENT '资源说明HTML',
  `usage_notice` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '使用说明',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0下线 1已发布',
  `is_recommended` TINYINT NOT NULL DEFAULT 0 COMMENT '是否推荐：0否 1是',
  `view_count` INT NOT NULL DEFAULT 0 COMMENT '浏览量',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序值，数值越大越靠前',
  `publish_time` DATETIME NULL DEFAULT NULL COMMENT '发布时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源主表';

CREATE TABLE `resource_preview` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `resource_id` BIGINT NOT NULL COMMENT '资源ID',
  `image_url` VARCHAR(255) NOT NULL COMMENT '预览图URL',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序值，数值越大越靠前',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源预览图表';

CREATE TABLE `resource_tag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `resource_id` BIGINT NOT NULL COMMENT '资源ID',
  `tag_id` BIGINT NOT NULL COMMENT '标签ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源标签关联表';

CREATE TABLE `resource_recommend` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `resource_id` BIGINT NOT NULL COMMENT '当前资源ID',
  `recommended_resource_id` BIGINT NOT NULL COMMENT '推荐资源ID',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序值，数值越大越靠前',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源推荐关联表';

CREATE TABLE `faq` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `question` VARCHAR(255) NOT NULL COMMENT '问题',
  `answer` TEXT NOT NULL COMMENT '回答',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序值，数值越大越靠前',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0禁用 1启用',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='常见问题表';

CREATE TABLE `lead` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(50) NOT NULL COMMENT '老师称呼',
  `contact` VARCHAR(100) NOT NULL COMMENT '联系方式，可填手机号或微信号',
  `source_page` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '来源页面路径',
  `message` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '咨询内容',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '线索状态：0待跟进 1已联系 2已成交 3已关闭',
  `follow_up_note` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '跟进备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='咨询线索表';

CREATE TABLE `site_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `config_key` VARCHAR(100) NOT NULL COMMENT '配置键',
  `config_value` TEXT NOT NULL COMMENT '配置值',
  `config_group` VARCHAR(50) NOT NULL DEFAULT 'site' COMMENT '配置分组，例如 site、home',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '配置说明',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点配置表';

CREATE TABLE `page_content` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `page_code` VARCHAR(50) NOT NULL COMMENT '页面编码，例如 about、contact',
  `title` VARCHAR(100) NOT NULL COMMENT '页面标题',
  `content_html` LONGTEXT NOT NULL COMMENT '页面HTML内容',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='固定页面内容表';

SET FOREIGN_KEY_CHECKS = 1;
